### ISSUE TITLE
Podman systemd units cause error

### ISSUE THREAD

**Issue by keraldi** [desbma/shh#23]
In attempting to use shh to apply hardening to a podman systemd user unit file, I encountered the following error:

```
systemctl --user status ArchiSteamFarm-nosecopt@tobias
○ ArchiSteamFarm-nosecopt@tobias.service - ArchiSteamFarm podman systemd unit
     Loaded: loaded (/home/tobias/.config/containers/systemd/ArchiSteamFarm-nosecopt@.container; generated)
     Active: inactive (dead)
       Docs: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker

Oct 27 01:14:12 errorserver systemd[134229]: ArchiSteamFarm-nosecopt@tobias.service: Main process exited, code=exited, status=137/n/a
Oct 27 01:14:12 errorserver ArchiSteamFarm-nosecopt@tobias[228352]: INFO  [shh] Detected versions: Systemd 257.9, Linux kernel 6.17.0, strace 6.16
Oct 27 01:14:12 errorserver ArchiSteamFarm-nosecopt@tobias[228352]: error: the following required arguments were not provided:
Oct 27 01:14:12 errorserver ArchiSteamFarm-nosecopt@tobias[228352]:   <PATHS>...
Oct 27 01:14:12 errorserver ArchiSteamFarm-nosecopt@tobias[228352]: Usage: shh merge-profile-data --instance <INSTANCE> --mode <MODE> --merge-paths-threshold <MERGE_PATHS_THRESHOLD> <PATHS>...
Oct 27 01:14:12 errorserver ArchiSteamFarm-nosecopt@tobias[228352]: For more information, try '--help'.
Oct 27 01:14:12 errorserver systemd[134229]: ArchiSteamFarm-nosecopt@tobias.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Oct 27 01:14:12 errorserver systemd[134229]: ArchiSteamFarm-nosecopt@tobias.service: Failed with result 'exit-code'.
Oct 27 01:14:12 errorserver systemd[134229]: Stopped ArchiSteamFarm-nosecopt@tobias.service - ArchiSteamFarm podman systemd unit.
Oct 27 01:14:12 errorserver systemd[134229]: ArchiSteamFarm-nosecopt@tobias.service: Consumed 2.620s CPU time, 173.2M memory peak.
```

The unit file is as follows:

```
# ArchiSteamFarm-nosecopt@.container 

[Unit]
Description=ArchiSteamFarm podman systemd unit
Documentation=https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
After=local-fs.target

[Container]
ContainerName=asf
Image=docker.io/justarchi/archisteamfarm:latest
# auto-updates based on registry image tag (unnecessary for `latest` which features auto-updating but might be useful for `main`
#AutoUpdate=registry
#PublishPort=127.0.0.1:1242:1242
#PublishPort=[::]:1242:1242
# read-only attribute not sensible for config as ASF wants to chown. Also IPC may write to config 
#Volume=/home/%i/ArchiSteamFarm:/app:z

[Install]
WantedBy=multi-user.target default.target

```

and the following shh --version

```
INFO  [shh] Detected versions: Systemd 257.9, Linux kernel 6.17.0, strace 6.16
systemd-hardening-helper 2025.10.22
```

It worked fine when attempted on a regular service file before. I am aware that the `strace` version is a bit outdated, I'll attempt to test it with a newer `strace` at a later point in time.

Commands used:
`$ shh service start-profile -i user ArchiSteamFarm-nosecopt@tobias`
```
INFO  [shh] Detected versions: Systemd 257.9, Linux kernel 6.17.0, strace 6.16
INFO  [shh] Current service exposure level: 10.0
INFO  [shh::systemd::service] Located unit config file(s): ["/home/tobias/.config/containers/systemd/ArchiSteamFarm-nosecopt@.container"]
INFO  [shh::systemd::service] Config fragment written in "/run/user/1000/systemd/user/ArchiSteamFarm-nosecopt@.service.d/zz_shh-profile.conf"
INFO  [shh::systemd::service] restart ArchiSteamFarm-nosecopt@tobias.service
```

`$ shh service finish-profile -i user ArchiSteamFarm-nosecopt@tobias` 
```
INFO  [shh] Detected versions: Systemd 257.9, Linux kernel 6.17.0, strace 6.16
-- No entries --
INFO  [shh::systemd::service] stop ArchiSteamFarm-nosecopt@tobias.service
INFO  [shh::systemd::service] "/run/user/1000/systemd/user/ArchiSteamFarm-nosecopt@.service.d/zz_shh-profile.conf" removed
WARN  [shh::systemd::service] Profiling result is not available after 3s (Unable to get profiling result snippet), this can be caused by slow service shutdown. Will retry and wait up to 90s 
Error: Timeout waiting for profiling result

Caused by:
    Unable to get profiling result snippet
```
(no result after 90s)

`$ podman info`

```
host:
  arch: amd64
  buildahVersion: 1.42.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.12-4_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: unknown'
  cpuUtilization:
    idlePercent: 99.57
    systemPercent: 0.24
    userPercent: 0.18
  cpus: 16
  databaseBackend: sqlite
  distribution:
    codename: questing
    distribution: ubuntu
    version: "25.10"
  eventLogger: journald
  freeLocks: 2039
  hostname: errorserver
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.17.0-5-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 17990901760
  memTotal: 32519376896
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: netavark_1.14.0-2_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.14.0
  ociRuntime:
    name: crun
    package: crun_1.21-1ubuntu2_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.21
      commit: 10269840aa07fb7e6b7e1acff6198692d8ff5c88
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20250503.587980c-2_amd64
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.1-1.1_amd64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.6.0
  swapFree: 24849616896
  swapTotal: 24849616896
  uptime: 71h 39m 0.00s (Approximately 2.96 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: registry-1.docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
    PullFromMirror: ""
  ghcr.io:
    Blocked: false
    Insecure: false
    Location: ghcr.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: ghcr.io
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/tobias/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /opt/containers/tobias/storage
  graphRootAllocated: 6001185964032
  graphRootUsed: 10027819008
  graphStatus:
    Build Version: Btrfs v6.16
    Library Version: "104"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /opt/containers/tobias/storage/volumes
version:
  APIVersion: 6.0.0-dev
  Built: 1761314662
  BuiltTime: Fri Oct 24 16:04:22 2025
  GitCommit: cfe5bdbe4676901d952a9415cbbd46cb6e8c516c
  GoVersion: go1.24.4
  Os: linux
  OsArch: linux/amd64
  Version: 6.0.0-dev
```

**Comment by desbma** [comment]
Thanks for the detailed report.

At first glance I think the issue is due `shh` reading and parsing the `.container` unit instead of the `.service` generated from it.

Can you paste the output of:
* `systemctl cat ArchiSteamFarm-nosecopt@tobias.service`
* `systemctl show -P FragmentPath ArchiSteamFarm-nosecopt@tobias.service`

**Comment by desbma** [comment]
It should be fixed in the [sd-cat branch](https://github.com/desbma/shh/tree/sd-cat), can you build from source to test and confirm?

**Comment by desbma** [comment]
Does the service work once you restart it with the hardening options applied?

**Comment by keraldi** [comment]
No, there are a few errors, presumably because it (podman) attempts to use capabilities that were filtered by `shh` (in the startup process already, so they should have been recorded by `shh`). Log attached.

[out.log](https://github.com/user-attachments/files/23251406/out.log)

With the following generator file:

```
[Service]
LockPersonality=true
RestrictRealtime=true
ProtectClock=true
MemoryDenyWriteExecute=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
SocketBindDeny=ipv6:udp
CapabilityBoundingSet=~CAP_BLOCK_SUSPEND CAP_BPF CAP_IPC_LOCK CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_MODULE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYSLOG CAP_WAKE_ALARM
SystemCallFilter=~@aio:EPERM @clock:EPERM @cpu-emulation:EPERM @debug:EPERM @memlock:EPERM @module:EPERM @obsolete:EPERM @pkey:EPERM @raw-io:EPERM @reboot:EPERM @swap:EPERM


[Unit]
Description=ArchiSteamFarm podman systemd unit
Documentation=https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
After=local-fs.target

[Container]
ContainerName=asf
Image=docker.io/justarchi/archisteamfarm:latest
# auto-updates based on registry image tag (unnecessary for `latest` which features auto-updating but might be useful for `main`
#AutoUpdate=registry
#PublishPort=127.0.0.1:1242:1242
#PublishPort=[::]:1242:1242
# read-only attribute not sensible for config as ASF wants to chown. Also IPC may write to config 
#Volume=/home/%i/ArchiSteamFarm:/app:z
PodmanArgs=--stop-timeout 60


[Install]
WantedBy=multi-user.target default.target
```

**Comment by keraldi** [comment]
1.1.:
 I'm running Ubuntu Server 25.10 with essentially default configuration, at least I'm not aware of having applied additional hardening.

ASF itself usually runs with the following hardening options if ran as a systemd service (without container):

```
# ASF security hardening, all of the below entries are optional, but their existence improves security of your system
CapabilityBoundingSet=
DevicePolicy=closed
LockPersonality=yes
NoNewPrivileges=yes
PrivateDevices=yes
PrivateIPC=yes
PrivateMounts=yes
PrivateUsers=yes
ProcSubset=pid
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=read-only
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectProc=invisible
ProtectSystem=strict
ReadWritePaths=/home/%i/ArchiSteamFarm /tmp
RemoveIPC=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SecureBits=noroot-locked
SystemCallArchitectures=native
SystemCallFilter=@system-service mincore
SystemCallFilter=~@privileged
UMask=0077
```

However, some of those are incompatible when running it inside podman via a podman systemd unit file.


1.2.:
 I could reliably get it running again with the following options:
```
[Service]
LockPersonality=true
RestrictRealtime=true
#ProtectClock=true
#MemoryDenyWriteExecute=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_UNIX
SocketBindDeny=ipv6:udp
#CapabilityBoundingSet=~CAP_BLOCK_SUSPEND CAP_BPF CAP_IPC_LOCK CAP_MKNOD CAP_NET_RAW CAP_PERFMON CAP_SYS_BOOT CAP_SYS_MODULE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_TIME CAP_SYSLOG CAP_WAKE_ALARM
SystemCallFilter=~@aio:EPERM @clock:EPERM @cpu-emulation:EPERM @debug:EPERM @memlock:EPERM @module:EPERM @obsolete:EPERM @pkey:EPERM @raw-io:EPERM @reboot:EPERM @swap:EPERM
#PrivateUsers=true
``` 
`Privateusers=true` seems to cause some issue with `podman`, as it would work with the regular systemd unit file but not when containerized.

2.:
 According to the maintainer of ArchiSteamFarm, the segfault likely happend due .net using JIT to transpile CIL into assembly. Removing `MemoryDenyWriteExecute=true` fixed the issue. However this probably should have been caught by `shh` when profiling as that happens already when .net initializes.

Do you still want the log file? I can try to find some time to add it tormorrow.


---

Aside from that, I feel satisfied with the results so far - I'm considering dropping my excursion into this topic as I cannot even remember why I started it and I won't have time in the coming weeks. 

Thank you a lot, I think I've learned a couple new things, too!

**Comment by desbma** [comment]
Don't bother with the log file, I have reproduced the segfault with another C# program, and it should be fixed by https://github.com/desbma/shh/commit/48fc22254ed37160f5efb627f78b4f51339e6dd1.

**Comment by kuflierl** [comment]
@badele the latest update fixing issues has still not yet found it's way into downstream. This PR https://github.com/NixOS/nixpkgs/pull/458470 is currently tracking it. Please try running it using this version.

`nix shell nixpkgs/fd2c2645e2c50b74be72069735335356156e36ef#shh`

You should get the version string 2025.11.3

**Comment by desbma** [comment]
Great, although I was half expecting you'd hit the same `Failed to drop capabilities: Operation not permitted` error @keraldi last had.

**Comment by Barnoux** [comment]
I think i found something interresting from https://www.redhat.com/en/blog/container-security-seccomp
Maybe, it's link to our issue. Maybe there is a race condition and we are losing  container's early syscall during start.

> The OCI seccomp bpf hook

> We implemented the syscall tracer as an Open Container Initiative (OCI) [runtime hook]> (https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks). OCI runtime hooks are called at different stages of a container's lifecycle and executed by OCI-compliant container runtimes, such as runc. Runc is used to spawn and run containers. It is the default runtime of Podman, containerd, Docker, and many other tools.

> Our syscall-tracing hook runs at the prestart stage, where the init process of the container is created but not yet started. We can extract the PID namespace of the container, compile the eBPF program, and start it. All this happens before the container is started, so we do not run into a race condition and avoid losing any of the container's early syscalls. Once the eBPF program is running, we detach it from the hook, and the container runtime can start the container.

**Comment by desbma** [comment]
Thanks, this is useful.

I have updated the [container branch](https://github.com/desbma/shh/tree/container) to now automatically disable the 4 problematic options if the unit is generated from a container template.
